name: dartup
version: 0.9.0
description: Library for servers on the dartup platform.
author: Ole Martin Gjersvik <olem@olem.org>
homepage: https://github.com/dartup/dartup_package
documentation:
dependencies:
dev_dependencies:
